<?php
/*
 *      www/lang/English.inc
 *      
 *      Copyright 2010 Daniel Böhmer <daniel.boehmer@it2007.ba-leipzig.de> and
 *                     Patrick Nicolaus <patrick.nicolaus@it2007.ba-leipzig.de>
 *      
 *      This file is part of Hotelres.
 * 
 *      Hotelres is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation; either version 2 of the License, or
 *      (at your option) any later version.
 *      
 *      Hotelres is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *      
 *      You should have received a copy of the GNU General Public License
 *      along with this program; if not, write to the Free Software
 *      Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 *      MA 02110-1301, USA.
 */

// LANGUAGE FILE FOR ENGLISH

// system: $translation["some built-in text"]="translated text";

// header
$translation["Eingeloggt als %s"]="Logged in as %s";
$translation["Ausloggen"]="Log out";
$translation["Sprache wählen"]="Select language";

// navigation bar
$translation["Start"]="Start";
$translation["Reservierung"]="Booking";
$translation["Belegungsplan"]="Schedule";
$translation["Benutzerverwaltung"]="User management";
$translation["Zimmerverwaltung"]="Room management";
$translation["Impressum"]="Imprint";

// imprint
$translation["Dieses Projekt wurde im Rahmen eines Software-Projekt für ein BA-Studium erstellt von"]=
        "This project was realized as a software project for a study at Berufsakademie Leipzig by";
$translation["und"]="and";
$translation["im %s. Semester"]="in the %s. term";
$translation["aus der Seminargruppe %s."]=
        "from the seminar group %s.";
$translation["Anschrift"]="Mail address";
$translation["Telefon"]="Phone";
$translation["E-Mail"]="E-mail";

?>
